In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('/Users/trumpalltweet.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (9,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df.head(10)

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1268564690143232001,1268564689069527042,1591284365000,2020-06-05,00:26:05,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
1,1268564689069527042,1268564689069527042,1591284365000,2020-06-05,00:26:05,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
2,1268552570617901058,1268552570617901058,1591281476000,2020-06-04,23:37:56,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
3,1268522581944082433,1268522581944082433,1591274326000,2020-06-04,21:38:46,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
4,1268497685553823745,1268497685553823745,1591268390000,2020-06-04,19:59:50,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
5,1268497398239842307,1268497398239842307,1591268321000,2020-06-04,19:58:41,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
6,1268497297702367235,1268497297702367235,1591268297000,2020-06-04,19:58:17,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
7,1268496433809952769,1268496433809952769,1591268092000,2020-06-04,19:54:52,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
8,1268496283649609730,1268496283649609730,1591268056000,2020-06-04,19:54:16,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
9,1268495510647836673,1268495510647836673,1591267871000,2020-06-04,19:51:11,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43127 entries, 0 to 43126
Data columns (total 34 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               43127 non-null  int64
 1   conversation_id  43127 non-null  int64
 2   created_at       43127 non-null  int64
 3   date             43127 non-null  object
 4   time             43127 non-null  object
 5   timezone         43127 non-null  object
 6   user_id          43127 non-null  int64
 7   username         43127 non-null  object
 8   name             43127 non-null  object
 9   place            77 non-null     object
 10  tweet            43127 non-null  object
 11  mentions         43127 non-null  object
 12  urls             43127 non-null  object
 13  photos           43127 non-null  object
 14  replies_count    43127 non-null  int64
 15  retweets_count   43127 non-null  int64
 16  likes_count      43127 non-null  int64
 17  hashtags         43127 non-null  object
 18  cashtags         43127 non-null  object
 19  link             43127 non-null  object
 20  retweet          43127 non-null  bool
 21  quote_url        1457 non-null   object
 22  video            43127 non-null  int64
 23  near             0 non-null      float64
 24  geo              0 non-null      float64
 25  source           0 non-null      float64
 26  user_rt_id       0 non-null      float64
 27  user_rt          0 non-null      float64
 28  retweet_id       0 non-null      float64
 29  reply_to         43127 non-null  object
 30  retweet_date     0 non-null      float64
 31  translate        0 non-null      float64
 32  trans_src        0 non-null      float64
 33  trans_dest       0 non-null      float64
dtypes: bool(1), float64(10), int64(8), object(15)
memory usage: 10.9+ MB

In [10]:
df[['time']]

           time
0      00:26:05
1      00:26:05
2      23:37:56
3      21:38:46
4      19:59:50
...         ...
43122  23:07:28
43123  05:40:15
43124  22:38:08
43125  10:00:10
43126  03:54:25

[43127 rows x 1 columns]

In [6]:
drop_list = ['id','conversation_id','created_at','name','timezone','user_id','cashtags','place','quote_url','near','geo','source','user_rt_id','user_rt','retweet_id','retweet_date','translate','trans_src','trans_dest','video','retweet']
df = df.drop(columns=drop_list)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43127 entries, 0 to 43126
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            43127 non-null  object
 1   time            43127 non-null  object
 2   username        43127 non-null  object
 3   tweet           43127 non-null  object
 4   mentions        43127 non-null  object
 5   urls            43127 non-null  object
 6   photos          43127 non-null  object
 7   replies_count   43127 non-null  int64
 8   retweets_count  43127 non-null  int64
 9   likes_count     43127 non-null  int64
 10  hashtags        43127 non-null  object
 11  link            43127 non-null  object
 12  reply_to        43127 non-null  object
dtypes: int64(3), object(10)
memory usage: 4.3+ MB

In [9]:
df

,date,time,username,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,link,reply_to
0,2020-06-05,00:26:05,realdonaldtrump,....I will never stop working to secure the re...,[],[],[],4048,9071,47695,[],https://twitter.com/realDonaldTrump/status/126...,"[{'user_id': '25073877', 'username': 'realDona..."
1,2020-06-05,00:26:05,realdonaldtrump,"I am to happy announce that Navy Veteran, Mich...",[],[],[],6113,18139,86882,[],https://twitter.com/realDonaldTrump/status/126...,"[{'user_id': '25073877', 'username': 'realDona..."
2,2020-06-04,23:37:56,realdonaldtrump,Please let this serve as my Complete and Total...,['lyndabennettnc'],[],[],8721,12934,49084,['#nc11'],https://twitter.com/realDonaldTrump/status/126...,"[{'user_id': '25073877', 'username': 'realDona..."
3,2020-06-04,21:38:46,realdonaldtrump,Disgraceful! https://twitter.com/donaldjtrumpj...,[],['https://twitter.com/donaldjtrumpjr/status/12...,[],9969,18053,71243,[],https://twitter.com/realDonaldTrump/status/126...,"[{'user_id': '25073877', 'username': 'realDona..."
4,2020-06-04,19:59:50,realdonaldtrump,MAKE AMERICA GREAT AGAIN!,[],[],[],76661,55458,309934,[],https://twitter.com/realDonaldTrump/status/126...,"[{'user_id': '25073877', 'username': 'realDona..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43122,2009-05-12,23:07:28,realdonaldtrump,"""My persona will never be that of a wallflower...",[],[],[],105,1377,1965,[],https://twitter.com/realDonaldTrump/status/177...,"[{'user_id': '25073877', 'username': 'realDona..."
43123,2009-05-09,05:40:15,realdonaldtrump,New Blog Post: Celebrity Apprentice Finale and...,[],[],[],9,11,27,[],https://twitter.com/realDonaldTrump/status/174...,"[{'user_id': '25073877', 'username': 'realDona..."
43124,2009-05-08,22:38:08,realdonaldtrump,Donald Trump reads Top Ten Financial Tips on L...,[],[],[],6,13,20,[],https://twitter.com/realDonaldTrump/status/173...,"[{'user_id': '25073877', 'username': 'realDona..."
43125,2009-05-05,10:00:10,realdonaldtrump,Donald Trump will be appearing on The View tom...,[],[],[],24,34,270,[],https://twitter.com/realDonaldTrump/status/170...,"[{'user_id': '25073877', 'username': 'realDona..."
43126,2009-05-05,03:54:25,realdonaldtrump,Be sure to tune in and watch Donald Trump on L...,[],[],[],205,510,912,[],https://twitter.com/realDonaldTrump/status/169...,"[{'user_id': '25073877', 'username': 'realDona..."

In [13]:
df[['tweet']]

                                                   tweet
0      ....I will never stop working to secure the re...
1      I am to happy announce that Navy Veteran, Mich...
2      Please let this serve as my Complete and Total...
3      Disgraceful! https://twitter.com/donaldjtrumpj...
4                              MAKE AMERICA GREAT AGAIN!
...                                                  ...
43122  "My persona will never be that of a wallflower...
43123  New Blog Post: Celebrity Apprentice Finale and...
43124  Donald Trump reads Top Ten Financial Tips on L...
43125  Donald Trump will be appearing on The View tom...
43126  Be sure to tune in and watch Donald Trump on L...

[43127 rows x 1 columns]

In [8]:
import texthero as hero

In [1]:
!pip3 install pytz

Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (2019.1)
You are using pip version 18.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [113]:
from datetime import datetime
from pytz import timezone
import pytz

In [10]:
import nest_asyncio
nest_asyncio.apply()!pip3 install twint

Requirement already satisfied: twint in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (2.1.20)
Requirement already satisfied: aiohttp in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (3.6.2)
Requirement already satisfied: aiodns in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (2.0.0)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (4.9.0)
Requirement already satisfied: cchardet in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (2.1.6)
Requirement already satisfied: elasticsearch in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (7.6.0)
Requirement already satisfied: pysocks in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (1.7.1)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (1.0.3)
Requirement already satisfied: aiohttp_socks in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (0.3.9)
Requirement already satisfied: schedule in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (0.6.0)
Requirement already satisfied: geopy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (1.21.0)
Requirement already satisfied: fake-useragent in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (0.1.11)
Requirement already satisfied: googletransx in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from twint) (2.4.2)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (1.1.0)
Requirement already satisfied: multidict<5.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (4.7.5)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (3.7.4.2)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (19.1.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (3.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (1.4.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiohttp->twint) (3.0.1)
Requirement already satisfied: typing; python_version < "3.7" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiodns->twint) (3.7.4.1)
Requirement already satisfied: pycares>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from aiodns->twint) (3.1.1)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from beautifulsoup4->twint) (2.0)
Requirement already satisfied: urllib3>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from elasticsearch->twint) (1.25.3)
Requirement already satisfied: numpy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pandas->twint) (1.16.4)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pandas->twint) (2019.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pandas->twint) (2.8.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from geopy->twint) (1.50)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from googletransx->twint) (2.22.0)
Requirement already satisfied: idna>=2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from idna-ssl>=1.0; python_version < "3.7"->aiohttp->twint) (2.8)
Requirement already satisfied: cffi>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pycares>=3.0.0->aiodns->twint) (1.14.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas->twint) (1.12.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->googletransx->twint) (2019.3.9)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->twint) (2.20)
You are using pip version 18.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [1]:
import twint

In [13]:
pwd

'/Users/maruyamakouta'

In [1]:
import datetime as dt
import re
import os
os.getcwd()
import nest_asyncio
nest_asyncio.apply()

In [2]:
import twint

In [ ]:
c = twint.Config()
c.Username = "realDonaldTrump"
c.Store_csv=True
c.Count=True
c.Since='2009-03-01'
c.Until = '2020-08-31'
c.Format="Tweet id:{id}| Date:{date}|Time:{time}|Tweet:{tweet}"
c.Custom['tweet']=['id','date','time','tweet']
c.Lowercase=True
twint.run.Search(c)

In [11]:
import pandas as pd

In [4]:
pwd

'/Users/maruyamakouta'

In [12]:
df=pd.read_csv('/Users/maruyamakouta/Desktop/trumptweetnewst/tweets.csv',low_memory=False,parse_dates=[['date', 'time']])

In [13]:
df.head(10)

,date_time,id,conversation_id,created_at,timezone,user_id,username,name,place,tweet,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,2020-08-30 21:04:05,1300041598449917953,1300041598449917953,1598789045000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,LAW & ORDER!!!,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
1,2020-08-30 20:51:49,1300038510687260673,1300038510687260673,1598788309000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,.@DNI_Ratcliffe on @MariaBartiromo this mornin...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
2,2020-08-30 20:48:34,1300037695729737733,1300037695729737733,1598788114000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,Moving along nicely. MAGA! https://twitter.com...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
3,2020-08-30 20:39:21,1300035375751221249,1300035375751221249,1598787561000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,Michael knows!!! https://twitter.com/LarrySchw...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
4,2020-08-30 20:12:32,1300028625283092481,1300028625283092481,1598785952000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,Their minds are gone!!! https://twitter.com/Ri...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
5,2020-08-30 20:08:59,1300027733293047810,1300027733293047810,1598785739000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,.@MayorBowser should arrest these agitators an...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
6,2020-08-30 19:59:06,1300025245626228736,1300025245626228736,1598785146000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,"The National Guard is Ready, Willing and Able....",...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
7,2020-08-30 19:56:39,1300024630930010112,1300024630930010112,1598784999000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,"Tone down the language, but TRUE! https://twit...",...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
8,2020-08-30 19:54:36,1300024113487138817,1300024113487138817,1598784876000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,This is where his crazed leaders are taking th...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
9,2020-08-30 19:49:50,1300022913060556802,1300022913060556802,1598784590000,JST,25073877,realdonaldtrump,Donald J. Trump,NaN,Thank you Lisa. Well stated!!! https://twitter...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN

In [14]:
df.describe()

,id,conversation_id,created_at,user_id,replies_count,retweets_count,likes_count,video,near,geo,source,user_rt_id,user_rt,retweet_id,retweet_date,translate,trans_src,trans_dest
count,4.439100e+04,4.439100e+04,4.439100e+04,44391.0,44391.000000,44391.000000,44391.000000,44391.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,6.572617e+17,6.572446e+17,1.445453e+12,25073877.0,5442.325133,6498.650740,27481.630195,0.040053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.379535e+17,3.379704e+17,8.075674e+10,0.0,11806.094160,11285.572702,49072.411965,0.196086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.698309e+09,1.698309e+09,1.241463e+12,25073877.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,3.680721e+17,3.680147e+17,1.376590e+12,25073877.0,20.000000,28.000000,30.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.912232e+17,5.912232e+17,1.429794e+12,25073877.0,136.000000,456.000000,455.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,9.451330e+17,9.451330e+17,1.514172e+12,25073877.0,5543.500000,11140.000000,47986.500000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.300042e+18,1.300042e+18,1.598789e+12,25073877.0,191969.000000,295675.000000,821591.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.describe

<bound method NDFrame.describe of                 date_time                   id      conversation_id  \
0     2020-08-30 21:04:05  1300041598449917953  1300041598449917953
1     2020-08-30 20:51:49  1300038510687260673  1300038510687260673
2     2020-08-30 20:48:34  1300037695729737733  1300037695729737733
3     2020-08-30 20:39:21  1300035375751221249  1300035375751221249
4     2020-08-30 20:12:32  1300028625283092481  1300028625283092481
...                   ...                  ...                  ...
44386 2009-05-12 23:07:28           1773561338           1773561338
44387 2009-05-09 05:40:15           1741160716           1741160716
44388 2009-05-08 22:38:08           1737479987           1737479987
44389 2009-05-05 10:00:10           1701461182           1701461182
44390 2009-05-05 03:54:25           1698308935           1698308935

          created_at timezone   user_id         username             name  \
0      1598789045000      JST  25073877  realdonaldtrump  Donald J. Trump
1      1598788309000      JST  25073877  realdonaldtrump  Donald J. Trump
2      1598788114000      JST  25073877  realdonaldtrump  Donald J. Trump
3      1598787561000      JST  25073877  realdonaldtrump  Donald J. Trump
4      1598785952000      JST  25073877  realdonaldtrump  Donald J. Trump
...              ...      ...       ...              ...              ...
44386  1242137248000      JST  25073877  realdonaldtrump  Donald J. Trump
44387  1241815215000      JST  25073877  realdonaldtrump  Donald J. Trump
44388  1241789888000      JST  25073877  realdonaldtrump  Donald J. Trump
44389  1241485210000      JST  25073877  realdonaldtrump  Donald J. Trump
44390  1241463265000      JST  25073877  realdonaldtrump  Donald J. Trump

      place                                              tweet  ... geo  \
0       NaN                                     LAW & ORDER!!!  ... NaN
1       NaN  .@DNI_Ratcliffe on @MariaBartiromo this mornin...  ... NaN
2       NaN  Moving along nicely. MAGA! https://twitter.com...  ... NaN
3       NaN  Michael knows!!! https://twitter.com/LarrySchw...  ... NaN
4       NaN  Their minds are gone!!! https://twitter.com/Ri...  ... NaN
...     ...                                                ...  ...  ..
44386   NaN  "My persona will never be that of a wallflower...  ... NaN
44387   NaN  New Blog Post: Celebrity Apprentice Finale and...  ... NaN
44388   NaN  Donald Trump reads Top Ten Financial Tips on L...  ... NaN
44389   NaN  Donald Trump will be appearing on The View tom...  ... NaN
44390   NaN  Be sure to tune in and watch Donald Trump on L...  ... NaN

      source user_rt_id  user_rt  retweet_id  \
0        NaN        NaN      NaN         NaN
1        NaN        NaN      NaN         NaN
2        NaN        NaN      NaN         NaN
3        NaN        NaN      NaN         NaN
4        NaN        NaN      NaN         NaN
...      ...        ...      ...         ...
44386    NaN        NaN      NaN         NaN
44387    NaN        NaN      NaN         NaN
44388    NaN        NaN      NaN         NaN
44389    NaN        NaN      NaN         NaN
44390    NaN        NaN      NaN         NaN

                                                reply_to retweet_date  \
0      [{'user_id': '25073877', 'username': 'realDona...          NaN
1      [{'user_id': '25073877', 'username': 'realDona...          NaN
2      [{'user_id': '25073877', 'username': 'realDona...          NaN
3      [{'user_id': '25073877', 'username': 'realDona...          NaN
4      [{'user_id': '25073877', 'username': 'realDona...          NaN
...                                                  ...          ...
44386  [{'user_id': '25073877', 'username': 'realDona...          NaN
44387  [{'user_id': '25073877', 'username': 'realDona...          NaN
44388  [{'user_id': '25073877', 'username': 'realDona...          NaN
44389  [{'user_id': '25073877', 'username': 'realDona...          NaN
44390  [{'user_id': '25073877', 'username': 'realDona...          NaN

      translate trans_src  trans_dest
0           NaN       NaN         NaN
1           NaN       NaN         NaN
2           NaN       NaN         NaN
3           NaN       NaN         NaN
4           NaN       NaN         NaN
...         ...       ...         ...
44386       NaN       NaN         NaN
44387       NaN       NaN         NaN
44388       NaN       NaN         NaN
44389       NaN       NaN         NaN
44390       NaN       NaN         NaN

[44391 rows x 33 columns]>

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44391 entries, 0 to 44390
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date_time        44391 non-null  datetime64[ns]
 1   id               44391 non-null  int64
 2   conversation_id  44391 non-null  int64
 3   created_at       44391 non-null  int64
 4   timezone         44391 non-null  object
 5   user_id          44391 non-null  int64
 6   username         44391 non-null  object
 7   name             44391 non-null  object
 8   place            76 non-null     object
 9   tweet            44391 non-null  object
 10  mentions         44391 non-null  object
 11  urls             44391 non-null  object
 12  photos           44391 non-null  object
 13  replies_count    44391 non-null  int64
 14  retweets_count   44391 non-null  int64
 15  likes_count      44391 non-null  int64
 16  hashtags         44391 non-null  object
 17  cashtags         44391 non-null  object
 18  link             44391 non-null  object
 19  retweet          44391 non-null  bool
 20  quote_url        1652 non-null   object
 21  video            44391 non-null  int64
 22  near             0 non-null      float64
 23  geo              0 non-null      float64
 24  source           0 non-null      float64
 25  user_rt_id       0 non-null      float64
 26  user_rt          0 non-null      float64
 27  retweet_id       0 non-null      float64
 28  reply_to         44391 non-null  object
 29  retweet_date     0 non-null      float64
 30  translate        0 non-null      float64
 31  trans_src        0 non-null      float64
 32  trans_dest       0 non-null      float64
dtypes: bool(1), datetime64[ns](1), float64(10), int64(8), object(13)
memory usage: 10.9+ MB

In [19]:
df[['retweet']].sum()

retweet    0
dtype: int64

In [21]:
drop_list=['id','conversation_id','created_at','name','timezone','user_id','cashtags','place','quote_url','near','geo','source','user_rt_id','user_rt','retweet_id','retweet_date','translate','trans_src','trans_dest','video','retweet']
df=df.drop(columns=drop_list)
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44391 entries, 0 to 44390
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date_time       44391 non-null  datetime64[ns]
 1   username        44391 non-null  object
 2   tweet           44391 non-null  object
 3   mentions        44391 non-null  object
 4   urls            44391 non-null  object
 5   photos          44391 non-null  object
 6   replies_count   44391 non-null  int64
 7   retweets_count  44391 non-null  int64
 8   likes_count     44391 non-null  int64
 9   hashtags        44391 non-null  object
 10  link            44391 non-null  object
 11  reply_to        44391 non-null  object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 4.1+ MB

None

In [22]:
!pip install texthero

# import texthero
import texthero as hero

Requirement already satisfied: texthero in /anaconda3/lib/python3.7/site-packages (1.0.9)
Requirement already satisfied: spacy>=2.2.2 in /anaconda3/lib/python3.7/site-packages (from texthero) (2.2.4)
Requirement already satisfied: pandas>=1.0.2 in /anaconda3/lib/python3.7/site-packages (from texthero) (1.0.3)
Requirement already satisfied: numpy>=1.17 in /anaconda3/lib/python3.7/site-packages (from texthero) (1.19.1)
Requirement already satisfied: plotly>=4.2.0 in /anaconda3/lib/python3.7/site-packages (from texthero) (4.9.0)
Requirement already satisfied: unidecode>=1.1.1 in /anaconda3/lib/python3.7/site-packages (from texthero) (1.1.1)
Requirement already satisfied: matplotlib>=3.1.0 in /anaconda3/lib/python3.7/site-packages (from texthero) (3.3.1)
Requirement already satisfied: tqdm>=4.3 in /anaconda3/lib/python3.7/site-packages (from texthero) (4.46.0)
Requirement already satisfied: wordcloud>=1.5.0 in /anaconda3/lib/python3.7/site-packages (from texthero) (1.8.0)
Requirement already satisfied: scikit-learn>=0.22 in /anaconda3/lib/python3.7/site-packages (from texthero) (0.23.1)
Requirement already satisfied: gensim>=3.6.0 in /anaconda3/lib/python3.7/site-packages (from texthero) (3.8.3)
Requirement already satisfied: nltk>=3.3 in /anaconda3/lib/python3.7/site-packages (from texthero) (3.4)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (1.1.3)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (1.0.2)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (1.0.0)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (0.4.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (1.0.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (3.0.2)
Requirement already satisfied: thinc==7.4.0 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (7.4.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (2.21.0)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (46.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (2.0.3)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /anaconda3/lib/python3.7/site-packages (from spacy>=2.2.2->texthero) (0.6.0)
Requirement already satisfied: pytz>=2017.2 in /anaconda3/lib/python3.7/site-packages (from pandas>=1.0.2->texthero) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /anaconda3/lib/python3.7/site-packages (from pandas>=1.0.2->texthero) (2.8.0)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from plotly>=4.2.0->texthero) (1.12.0)
Requirement already satisfied: retrying>=1.3.3 in /anaconda3/lib/python3.7/site-packages (from plotly>=4.2.0->texthero) (1.3.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /anaconda3/lib/python3.7/site-packages (from matplotlib>=3.1.0->texthero) (2.3.1)
Requirement already satisfied: pillow>=6.2.0 in /anaconda3/lib/python3.7/site-packages (from matplotlib>=3.1.0->texthero) (7.2.0)
Requirement already satisfied: cycler>=0.10 in /anaconda3/lib/python3.7/site-packages (from matplotlib>=3.1.0->texthero) (0.10.0)
Requirement already satisfied: certifi>=2020.06.20 in /anaconda3/lib/python3.7/site-packages (from matplotlib>=3.1.0->texthero) (2020.6.20)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib>=3.1.0->texthero) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.22->texthero) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.22->texthero) (0.14.1)
Requirement already satisfied: scipy>=0.19.1 in /anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.22->texthero) (1.4.1)
Requirement already satisfied: smart-open>=1.8.1 in /anaconda3/lib/python3.7/site-packages (from gensim>=3.6.0->texthero) (2.1.1)
Requirement already satisfied: singledispatch in /anaconda3/lib/python3.7/site-packages (from nltk>=3.3->texthero) (3.4.0.3)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /anaconda3/lib/python3.7/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->texthero) (1.6.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->texthero) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->texthero) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.2.2->texthero) (1.24.1)
Requirement already satisfied: boto3 in /anaconda3/lib/python3.7/site-packages (from smart-open>=1.8.1->gensim>=3.6.0->texthero) (1.14.43)
Requirement already satisfied: boto in /anaconda3/lib/python3.7/site-packages (from smart-open>=1.8.1->gensim>=3.6.0->texthero) (2.49.0)
Requirement already satisfied: zipp>=0.5 in /anaconda3/lib/python3.7/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<1.1.0,>=0.0.7->spacy>=2.2.2->texthero) (3.1.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /anaconda3/lib/python3.7/site-packages (from boto3->smart-open>=1.8.1->gensim>=3.6.0->texthero) (0.10.0)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /anaconda3/lib/python3.7/site-packages (from boto3->smart-open>=1.8.1->gensim>=3.6.0->texthero) (0.3.3)
Requirement already satisfied: botocore<1.18.0,>=1.17.43 in /anaconda3/lib/python3.7/site-packages (from boto3->smart-open>=1.8.1->gensim>=3.6.0->texthero) (1.17.43)
Requirement already satisfied: docutils<0.16,>=0.10 in /anaconda3/lib/python3.7/site-packages (from botocore<1.18.0,>=1.17.43->boto3->smart-open>=1.8.1->gensim>=3.6.0->texthero) (0.14)
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/anaconda3/bin/python -m pip install --upgrade pip' command.

In [23]:
df.head()

,date_time,username,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,link,reply_to
0,2020-08-30 21:04:05,realdonaldtrump,LAW & ORDER!!!,[],[],[],83354,61236,341338,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
1,2020-08-30 20:51:49,realdonaldtrump,.@DNI_Ratcliffe on @MariaBartiromo this mornin...,"['dni_ratcliffe', 'mariabartiromo', 'foxnews']",[],[],4516,9067,46725,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2,2020-08-30 20:48:34,realdonaldtrump,Moving along nicely. MAGA! https://twitter.com...,[],['https://twitter.com/PollWatch2020/status/129...,[],10223,16830,68409,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
3,2020-08-30 20:39:21,realdonaldtrump,Michael knows!!! https://twitter.com/LarrySchw...,[],['https://twitter.com/LarrySchweikart/status/1...,[],2817,8810,38403,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
4,2020-08-30 20:12:32,realdonaldtrump,Their minds are gone!!! https://twitter.com/Ri...,[],['https://twitter.com/RichLowry/status/1299436...,[],3752,8488,35030,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."

In [24]:
from datetime import datetime

In [25]:
from pytz import timezone

In [27]:
df['conv_datetime'] = df['date_time'].dt.tz_localize('Asia/Tokyo').dt.tz_convert('US/Eastern')

In [29]:
df.head(10)

,date_time,username,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,link,reply_to,conv_datetime
0,2020-08-30 21:04:05,realdonaldtrump,LAW & ORDER!!!,[],[],[],83354,61236,341338,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 08:04:05-04:00
1,2020-08-30 20:51:49,realdonaldtrump,.@DNI_Ratcliffe on @MariaBartiromo this mornin...,"['dni_ratcliffe', 'mariabartiromo', 'foxnews']",[],[],4516,9067,46725,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 07:51:49-04:00
2,2020-08-30 20:48:34,realdonaldtrump,Moving along nicely. MAGA! https://twitter.com...,[],['https://twitter.com/PollWatch2020/status/129...,[],10223,16830,68409,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 07:48:34-04:00
3,2020-08-30 20:39:21,realdonaldtrump,Michael knows!!! https://twitter.com/LarrySchw...,[],['https://twitter.com/LarrySchweikart/status/1...,[],2817,8810,38403,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 07:39:21-04:00
4,2020-08-30 20:12:32,realdonaldtrump,Their minds are gone!!! https://twitter.com/Ri...,[],['https://twitter.com/RichLowry/status/1299436...,[],3752,8488,35030,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 07:12:32-04:00
5,2020-08-30 20:08:59,realdonaldtrump,.@MayorBowser should arrest these agitators an...,['mayorbowser'],['https://twitter.com/RichLowry/status/1299516...,[],3217,10924,36245,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 07:08:59-04:00
6,2020-08-30 19:59:06,realdonaldtrump,"The National Guard is Ready, Willing and Able....",[],['https://twitter.com/stillgray/status/1299510...,[],4079,14029,50497,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 06:59:06-04:00
7,2020-08-30 19:56:39,realdonaldtrump,"Tone down the language, but TRUE! https://twit...",[],['https://twitter.com/LATiffani1/status/129968...,[],5057,19239,84225,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 06:56:39-04:00
8,2020-08-30 19:54:36,realdonaldtrump,This is where his crazed leaders are taking th...,[],['https://twitter.com/BuzzPatterson/status/130...,[],3347,8732,31964,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 06:54:36-04:00
9,2020-08-30 19:49:50,realdonaldtrump,Thank you Lisa. Well stated!!! https://twitter...,[],['https://twitter.com/LisaMarieBoothe/status/1...,[],1981,8919,32859,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona...",2020-08-30 06:49:50-04:00

In [31]:
df['datetime']=df['conv_datetime'].dt.tz_localize(None)

In [32]:
df=df.drop(columns=['date_time','conv_datetime'])
df=df.set_index('datetime')

In [33]:
df.head(20)

,username,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,link,reply_to
datetime,,,,,,,,,,,
2020-08-30 08:04:05,realdonaldtrump,LAW & ORDER!!!,[],[],[],83354,61236,341338,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 07:51:49,realdonaldtrump,.@DNI_Ratcliffe on @MariaBartiromo this mornin...,"['dni_ratcliffe', 'mariabartiromo', 'foxnews']",[],[],4516,9067,46725,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 07:48:34,realdonaldtrump,Moving along nicely. MAGA! https://twitter.com...,[],['https://twitter.com/PollWatch2020/status/129...,[],10223,16830,68409,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 07:39:21,realdonaldtrump,Michael knows!!! https://twitter.com/LarrySchw...,[],['https://twitter.com/LarrySchweikart/status/1...,[],2817,8810,38403,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 07:12:32,realdonaldtrump,Their minds are gone!!! https://twitter.com/Ri...,[],['https://twitter.com/RichLowry/status/1299436...,[],3752,8488,35030,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 07:08:59,realdonaldtrump,.@MayorBowser should arrest these agitators an...,['mayorbowser'],['https://twitter.com/RichLowry/status/1299516...,[],3217,10924,36245,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:59:06,realdonaldtrump,"The National Guard is Ready, Willing and Able....",[],['https://twitter.com/stillgray/status/1299510...,[],4079,14029,50497,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:56:39,realdonaldtrump,"Tone down the language, but TRUE! https://twit...",[],['https://twitter.com/LATiffani1/status/129968...,[],5057,19239,84225,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:54:36,realdonaldtrump,This is where his crazed leaders are taking th...,[],['https://twitter.com/BuzzPatterson/status/130...,[],3347,8732,31964,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:49:50,realdonaldtrump,Thank you Lisa. Well stated!!! https://twitter...,[],['https://twitter.com/LisaMarieBoothe/status/1...,[],1981,8919,32859,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:42:13,realdonaldtrump,Thank you. We will not let them down! https://...,[],['https://twitter.com/FrankelJeremy/status/129...,[],1739,9846,38918,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:39:34,realdonaldtrump,Play Football Big Ten! https://twitter.com/abd...,[],['https://twitter.com/abdulamemon/status/12998...,[],2532,8524,50795,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:37:39,realdonaldtrump,GREAT PATRIOTS! https://twitter.com/JackPosobi...,[],['https://twitter.com/JackPosobiec/status/1299...,[],10616,30148,146243,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:36:14,realdonaldtrump,Disgraceful Anarchists. We are watching them c...,[],['https://twitter.com/KarluskaP/status/1299902...,[],8315,21628,72795,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:31:53,realdonaldtrump,Democrat “Leadership” has no clue. Request hel...,[],['https://twitter.com/mrandyngo/status/1299934...,[],3211,11202,35661,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:28:46,realdonaldtrump,ANTIFA is a Radical Left group that only wants...,[],['https://twitter.com/stillgray/status/1299932...,[],8413,23939,69035,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:18:46,realdonaldtrump,"Wheeler is incompetent, much like Sleepy Joe B...",[],['https://twitter.com/stattisconie/status/1299...,[],4393,8409,31046,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:12:58,realdonaldtrump,Our great National Guard could solve these pro...,[],['https://twitter.com/hollandcourtney/status/1...,[],5335,10877,36205,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 06:00:01,realdonaldtrump,The big backlash going on in Portland cannot b...,[],['https://twitter.com/ByMikeBaker/status/12999...,[],11957,19637,66553,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."
2020-08-30 05:49:43,realdonaldtrump,Everything a Governor asked the Federal Govern...,[],[],[],8421,20839,91526,[],https://twitter.com/realDonaldTrump/status/130...,"[{'user_id': '25073877', 'username': 'realDona..."

In [74]:
drop_list3=['username','mentions','urls','photos','hashtags','link','id','conversation_id','created_at','name','timezone','user_id','cashtags','place','quote_url','near','geo','source','user_rt_id','user_rt','retweet_id','retweet_date','translate','trans_src','trans_dest','video','retweet']

In [39]:
df=df.drop(columns=drop_list)

In [40]:
df.describe()

       replies_count  retweets_count    likes_count
count   44391.000000    44391.000000   44391.000000
mean     5442.325133     6498.650740   27481.630195
std     11806.094160    11285.572702   49072.411965
min         0.000000        0.000000       0.000000
25%        20.000000       28.000000      30.000000
50%       136.000000      456.000000     455.000000
75%      5543.500000    11140.000000   47986.500000
max    191969.000000   295675.000000  821591.000000

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 44391 entries, 2020-08-30 08:04:05 to 2009-05-04 14:54:25
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tweet           44391 non-null  object
 1   replies_count   44391 non-null  int64
 2   retweets_count  44391 non-null  int64
 3   likes_count     44391 non-null  int64
 4   reply_to        44391 non-null  object
dtypes: int64(3), object(2)
memory usage: 2.0+ MB

In [43]:
df.to_csv("トランプ分析用.csv")

In [44]:
pwd

'/Users/maruyamakouta'

In [46]:
df3=pd.read_csv('/Users/maruyamakouta/Downloads/trumptweet2009-20200831collab.csv',low_memory=False,parse_dates=[['date', 'time']])

In [47]:
df3.head()

,date_time,id,conversation_id,created_at,timezone,user_id,username,name,place,tweet,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,2020-08-30 22:16:33,1300195730527784960,1300195730527784960,1598825793000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Rushing him out of basement after seeing some ...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
1,2020-08-30 22:07:17,1300193398477946883,1300193398477946883,1598825237000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Rest In Peace Jay! https://twitter.com/AmyKrem...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
2,2020-08-30 22:05:50,1300193033581928448,1300193033581928448,1598825150000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,A weak and pathetic Democrat Mayor!!! https://...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
3,2020-08-30 20:38:48,1300171130326716418,1300171130326716418,1598819928000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,The only way you will stop the violence in the...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
4,2020-08-30 20:36:36,1300170579048357894,1300170576515026945,1598819796000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,"..The people of Portland, like all other citie...",...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN

In [75]:
df3=df3.drop(columns=drop_list3)

In [76]:
df3['conv_datetime'] = df3['date_time'].dt.tz_localize('UTC').dt.tz_convert('US/Eastern')

In [77]:
df3.head()

,date_time,tweet,replies_count,retweets_count,likes_count,conv_datetime
0,2020-08-30 22:16:33,Rushing him out of basement after seeing some ...,20367,22379,87062,2020-08-30 18:16:33-04:00
1,2020-08-30 22:07:17,Rest In Peace Jay! https://twitter.com/AmyKrem...,19454,61427,211074,2020-08-30 18:07:17-04:00
2,2020-08-30 22:05:50,A weak and pathetic Democrat Mayor!!! https://...,9378,18225,67037,2020-08-30 18:05:50-04:00
3,2020-08-30 20:38:48,The only way you will stop the violence in the...,54086,46314,245625,2020-08-30 16:38:48-04:00
4,2020-08-30 20:36:36,"..The people of Portland, like all other citie...",8627,19238,78253,2020-08-30 16:36:36-04:00

In [54]:
drop_list2=['id','conversation_id','created_at','name','timezone','user_id','cashtags','place','quote_url','near','geo','source','user_rt_id','user_rt','retweet_id','retweet_date','translate','trans_src','trans_dest','video','retweet']

In [73]:
df3

,date_time,id,conversation_id,created_at,timezone,user_id,username,name,place,tweet,...,near,geo,source,user_rt_id,user_rt,retweet_id,retweet_date,translate,trans_src,trans_dest
0,2020-08-30 22:16:33,1300195730527784960,1300195730527784960,1598825793000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Rushing him out of basement after seeing some ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-08-30 22:07:17,1300193398477946883,1300193398477946883,1598825237000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Rest In Peace Jay! https://twitter.com/AmyKrem...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-08-30 22:05:50,1300193033581928448,1300193033581928448,1598825150000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,A weak and pathetic Democrat Mayor!!! https://...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-08-30 20:38:48,1300171130326716418,1300171130326716418,1598819928000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,The only way you will stop the violence in the...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-08-30 20:36:36,1300170579048357894,1300170576515026945,1598819796000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,"..The people of Portland, like all other citie...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44393,2009-05-12 14:07:28,1773561338,1773561338,1242137248000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,"""My persona will never be that of a wallflower...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44394,2009-05-08 20:40:15,1741160716,1741160716,1241815215000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,New Blog Post: Celebrity Apprentice Finale and...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44395,2009-05-08 13:38:08,1737479987,1737479987,1241789888000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Donald Trump reads Top Ten Financial Tips on L...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44396,2009-05-05 01:00:10,1701461182,1701461182,1241485210000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Donald Trump will be appearing on The View tom...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44397,2009-05-04 18:54:25,1698308935,1698308935,1241463265000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Be sure to tune in and watch Donald Trump on L...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
df3['datetime'] = df3['conv_datetime'].dt.tz_localize(None)

# dropping the extra columns and setting the datetime as index.
df3 = df3.drop(columns=['date_time','conv_datetime'])
df3 = df3.set_index('datetime')

In [98]:
df3=df3.reset_index()

In [99]:
df3

,datetime,tweet,replies_count,retweets_count,likes_count
0,2020-08-30 18:16:33,Rushing him out of basement after seeing some ...,20367,22379,87062
1,2020-08-30 18:07:17,Rest In Peace Jay! https://twitter.com/AmyKrem...,19454,61427,211074
2,2020-08-30 18:05:50,A weak and pathetic Democrat Mayor!!! https://...,9378,18225,67037
3,2020-08-30 16:38:48,The only way you will stop the violence in the...,54086,46314,245625
4,2020-08-30 16:36:36,"..The people of Portland, like all other citie...",8627,19238,78253
...,...,...,...,...,...
44393,2009-05-12 10:07:28,"""My persona will never be that of a wallflower...",106,1343,1901
44394,2009-05-08 16:40:15,New Blog Post: Celebrity Apprentice Finale and...,11,11,24
44395,2009-05-08 09:38:08,Donald Trump reads Top Ten Financial Tips on L...,46,15,33
44396,2009-05-04 21:00:10,Donald Trump will be appearing on The View tom...,25,34,259
44397,2009-05-04 14:54:25,Be sure to tune in and watch Donald Trump on L...,215,513,938

In [95]:
df3

,tweet,replies_count,retweets_count,likes_count
datetime,,,,
2020-08-30 18:16:33,Rushing him out of basement after seeing some ...,20367,22379,87062
2020-08-30 18:07:17,Rest In Peace Jay! https://twitter.com/AmyKrem...,19454,61427,211074
2020-08-30 18:05:50,A weak and pathetic Democrat Mayor!!! https://...,9378,18225,67037
2020-08-30 16:38:48,The only way you will stop the violence in the...,54086,46314,245625
2020-08-30 16:36:36,"..The people of Portland, like all other citie...",8627,19238,78253
...,...,...,...,...
2009-05-12 10:07:28,"""My persona will never be that of a wallflower...",106,1343,1901
2009-05-08 16:40:15,New Blog Post: Celebrity Apprentice Finale and...,11,11,24
2009-05-08 09:38:08,Donald Trump reads Top Ten Financial Tips on L...,46,15,33
2009-05-04 21:00:10,Donald Trump will be appearing on The View tom...,25,34,259
2009-05-04 14:54:25,Be sure to tune in and watch Donald Trump on L...,215,513,938

In [105]:
df3['datetime'] = df3['datetime'].dt.tz_localize('UTC')

In [111]:
df3['datetime']

0       2020-08-30 18:16:33+00:00
1       2020-08-30 18:07:17+00:00
2       2020-08-30 18:05:50+00:00
3       2020-08-30 16:38:48+00:00
4       2020-08-30 16:36:36+00:00
                   ...
44393   2009-05-12 10:07:28+00:00
44394   2009-05-08 16:40:15+00:00
44395   2009-05-08 09:38:08+00:00
44396   2009-05-04 21:00:10+00:00
44397   2009-05-04 14:54:25+00:00
Name: datetime, Length: 44398, dtype: datetime64[ns, UTC]

In [116]:
df3['datetime'] = df3['datetime'].dt.tz.timezone('US/Eastern')

AttributeError: 'America/New_York' object has no attribute 'timezone'

In [115]:
df3['datetime']= df3['datetime'].dt.tz_convert(ny_tz)

In [114]:
ny_tz = pytz.timezone('America/New_York')

In [123]:
print(df3['datetime'])

0       2020-08-30 14:16:33-04:00
1       2020-08-30 14:07:17-04:00
2       2020-08-30 14:05:50-04:00
3       2020-08-30 12:38:48-04:00
4       2020-08-30 12:36:36-04:00
                   ...
44393   2009-05-12 06:07:28-04:00
44394   2009-05-08 12:40:15-04:00
44395   2009-05-08 05:38:08-04:00
44396   2009-05-04 17:00:10-04:00
44397   2009-05-04 10:54:25-04:00
Name: datetime, Length: 44398, dtype: datetime64[ns, America/New_York]

In [124]:
ny_tz.normalize(ny_tz )

AttributeError: 'America/New_York' object has no attribute 'tzinfo'

In [122]:
eastern = pytz.timezone('US/Eastern')

In [125]:
df4=pd.read_csv('/Users/maruyamakouta/Desktop/trumptweet2009-20200831collab.csv',low_memory=False,parse_dates=[['date', 'time']])

In [126]:
df4

,date_time,id,conversation_id,created_at,timezone,user_id,username,name,place,tweet,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,2020-08-30 22:16:33,1300195730527784960,1300195730527784960,1598825793000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Rushing him out of basement after seeing some ...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
1,2020-08-30 22:07:17,1300193398477946883,1300193398477946883,1598825237000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Rest In Peace Jay! https://twitter.com/AmyKrem...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
2,2020-08-30 22:05:50,1300193033581928448,1300193033581928448,1598825150000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,A weak and pathetic Democrat Mayor!!! https://...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
3,2020-08-30 20:38:48,1300171130326716418,1300171130326716418,1598819928000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,The only way you will stop the violence in the...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
4,2020-08-30 20:36:36,1300170579048357894,1300170576515026945,1598819796000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,"..The people of Portland, like all other citie...",...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44393,2009-05-12 14:07:28,1773561338,1773561338,1242137248000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,"""My persona will never be that of a wallflower...",...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
44394,2009-05-08 20:40:15,1741160716,1741160716,1241815215000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,New Blog Post: Celebrity Apprentice Finale and...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
44395,2009-05-08 13:38:08,1737479987,1737479987,1241789888000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Donald Trump reads Top Ten Financial Tips on L...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
44396,2009-05-05 01:00:10,1701461182,1701461182,1241485210000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Donald Trump will be appearing on The View tom...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN
44397,2009-05-04 18:54:25,1698308935,1698308935,1241463265000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,Be sure to tune in and watch Donald Trump on L...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN

In [132]:
df4.query("tweet.str.contains('Biggest Tax Increase')", engine='python')

,date_time,id,conversation_id,created_at,timezone,user_id,username,name,place,tweet,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
44038,2011-07-19 19:58:21,93409358674796544,93409358674796544,1311105501000,UTC,25073877,realdonaldtrump,Donald J. Trump,NaN,http://onforb.es/cDzmaN\r http://onforb.es/cD...,...,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '25073877', 'username': 'realDona...",NaN,NaN,NaN,NaN

In [135]:
df4.iloc[44038]

date_time                                        2011-07-19 19:58:21
id                                                 93409358674796544
conversation_id                                    93409358674796544
created_at                                             1311105501000
timezone                                                         UTC
user_id                                                     25073877
username                                             realdonaldtrump
name                                                 Donald J. Trump
place                                                            NaN
tweet               http://onforb.es/cDzmaN\r http://onforb.es/cD...
mentions                                                          []
urls                                                              []
photos                                                            []
replies_count                                                     45
retweets_count                                                    74
likes_count                                                       10
hashtags                                                          []
cashtags                                                          []
link               https://twitter.com/realDonaldTrump/status/934...
retweet                                                        False
quote_url                                                        NaN
video                                                              0
near                                                             NaN
geo                                                              NaN
source                                                           NaN
user_rt_id                                                       NaN
user_rt                                                          NaN
retweet_id                                                       NaN
reply_to           [{'user_id': '25073877', 'username': 'realDona...
retweet_date                                                     NaN
translate                                                        NaN
trans_src                                                        NaN
trans_dest                                                       NaN
Name: 44038, dtype: object

In [138]:
s=df4['tweet']

In [139]:
print(s[44038])

Obamacare is The Biggest Tax Increase In U.S. History--repeal it as part of any deal.

In [141]:
df5=pd.read_csv('/Users/maruyamakouta/Desktop/トランプツイート（サマータイム未反映）.csv',low_memory=False)

In [142]:
df5

,datetime,tweet,replies_count,retweets_count,likes_count
0,2020-08-30 18:16:33,Rushing him out of basement after seeing some ...,20367.0,22379.0,87062.0
1,2020-08-30 18:07:17,Rest In Peace Jay! https://twitter.com/AmyKrem...,19454.0,61427.0,211074.0
2,2020-08-30 18:05:50,A weak and pathetic Democrat Mayor!!! https://...,9378.0,18225.0,67037.0
3,2020-08-30 16:38:48,The only way you will stop the violence in the...,54086.0,46314.0,245625.0
4,2020-08-30 16:36:36,"Ted Wheeler, the wacky Radical Left Do Nothing...",15402.0,32712.0,126496.0
...,...,...,...,...,...
44397,2009-05-04 14:54:25,Be sure to tune in and watch Donald Trump on L...,215.0,513.0,938.0
44398,NaN,NaN,NaN,NaN,NaN
44399,NaN,NaN,NaN,NaN,NaN
44400,NaN,NaN,NaN,NaN,NaN
44401,NaN,NaN,NaN,NaN,NaN

In [144]:
df5['tweet'].str.lower()

0        rushing him out of basement after seeing some ...
1        rest in peace jay! https://twitter.com/amykrem...
2        a weak and pathetic democrat mayor!!! https://...
3        the only way you will stop the violence in the...
4        ted wheeler, the wacky radical left do nothing...
                               ...
44397    be sure to tune in and watch donald trump on l...
44398                                                  NaN
44399                                                  NaN
44400                                                  NaN
44401                                                  NaN
Name: tweet, Length: 44402, dtype: object